---
title: "SEED Experiment 1"
author: "Morgan Shumaker"
output: github_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(pacman) 
p_load(tidyverse, dplyr, devtools, ggplot2, gplots, skimr, markdown, rmarkdown, broom, ggridges, readxl, BSDA, scales, ggthemes)
```

## Importing Data 
```{r - long}
SEED_Exp1 <- read_xlsx("R_Exp1_SEED.xlsx")
```

```{r - wide}
SEED_Exp1_wide <- read_xlsx("R_Exp1SEED_wide.xlsx")
```

## Errorless
To run a z-test with this package (BSDA), the data needs to be in a data frame
so that R recognizes it as an object:
```{r}
SEED_Exp1_wide <- data.frame(SEED_Exp1_wide)
```

*Create data frames*
```{r}
  Older_Errorless <- data.frame(SEED_Exp1_wide$Older_Errorless)
```

```{r}
  Younger_Errorless <- data.frame(SEED_Exp1_wide$Younger_Errorless)
```

*Z test*
```{r}
  z.test(x = Older_Errorless, y = Younger_Errorless, alternative = "two.sided", mu = 0, sigma.x = 15, sigma.y = 15)
```

## Errorful
*Create data frames*
```{r}
  Older_Errorful <- data.frame(SEED_Exp1_wide$Older_Errorful)
```

```{r}
  Younger_Errorful <- data.frame(SEED_Exp1_wide$Younger_Erroful)
```

*Z test*
```{r}
  z.test(x = Older_Errorful, y = Younger_Errorful, alternative = "two.sided", mu = 0, sigma.x = 15, sigma.y = 15)
```

## Graphics
```{r}
SEED_Plots <- read_xlsx("SEED_Exp1_RPlots.xlsx")
```


```{r}
SEED_Plots <- SEED_Plots %>%
  mutate(Metacog = case_when(Metacognition == "0" ~ "Errorless",
                             Metacognition == "1" ~ "Errorful",
                             TRUE ~ as.character(Metacognition)))
```

```{r}
ggplot(SEED_Plots, aes(x = Age_Group, fill = Condition)) + geom_bar(position = "stack") +  facet_wrap(~Metacog) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  labs(x = "Age Group", y = "Percent") + 
  theme_minimal() + theme(panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank()) 
  
```
